version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db-server
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ismedi
      MYSQL_USER: ismedi_user
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"

  be:
    image: yujin20fd/ismedi-be:latest
    container_name: be-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./config:/config

volumes:
  db-data:
