name: ismedi CI/CD

on:
  push:
    branches:
      - infra/9-cicd

jobs:
  build-and-deploy:
    name: 빌드 및 배포
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v2

      - name: JDK 설정
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Gradle 실행 권한 부여
        run: chmod +x gradlew

      - name: Gradle 빌드 (테스트 제외)
        run: ./gradlew clean build -x test

      - name: DockerHub 로그인
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ismedi-be .
          docker push ${{ secrets.DOCKER_USERNAME }}/ismedi-be
